### ISSUE TITLE
NameError: global name 're' is not defined

### ISSUE THREAD

**Issue by jmcerrejon** [jbonet/TuSubtitulo.py#1]
```
Traceback (most recent call last):
  File "tusubseeker.py", line 177, in <module>
    folderSearch(args.folder)
  File "tusubseeker.py", line 94, in folderSearch
    match = re.search(rx, mkvfile, re.IGNORECASE)
NameError: global name 're' is not defined

```

**Comment by jbonet** [comment]
Fixed in e2a8d19
